const telaInicial = {
    search: '#search_query_top',    
    searchButton: '#searchbox > .btn',   
    result: '.btn btn-default button-search',
    more: '.lnk_view > span',
    qtde: '#quantity_wanted',
    color: '#color_14',
    size: '#group_1',
    add: '#add_to_cart',
    checkout: '.button-medium > span',
    qtdeCheckout: '#layer_cart_product_quantity',
    qtdeCheckout2: '.quantity_1_4_0_0_hidden',
    table: '#cart_summary',
    tbody: 'tbody',
    stock: '.label',
    next: '.cart_navigation > .button > span',
    createAccount: '#SubmitCreate > span',
    email: '#email_create',

    genero: '#id_gender1',
    pNome: '#customer_firstname',
    sNome: '#customer_lastname',
    senha: '#passwd',
    dia: '#days',
    mes: '#months',
    ano: '#years',
    empresa: '#company',
    endereco: '#address1',
    cidade: '#city',
    estado: '#id_state',
    cep: '#postcode',
    celular: '#phone_mobile',
    enderAlternativo: '#alias',
    cadastrar: '#submitAccount',


    confNome: '#address_delivery > .address_firstname',
    confEmpresa: '#address_delivery > .address_company',
    confEnder: '#address_delivery > .address_address1',
    confCidade: '#address_delivery > .address_city',
    confPais: '#address_delivery > .address_country_name',
    confCelular: '#address_delivery > .address_phone_mobile',
    pCheckout: '.cart_navigation > .button > span',
    termos: '#cgv',
    fPagamento: '.bankwire',
    total: '#total_product',

    preçoUnit: '.price',
    fqtde: '.cart_quantity',
    
};

export { telaInicial };
